version: "3.1"

networks:
  default:
    driver: bridge

services:
  spa:
    image: websec-spa
    build:
      context: ./SPA
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
     - default 

  api:
    image: websec-api
    build:
      context: ./API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5172
    ports:
      - "5172:5172"
    networks:
     - default        